import { useEffect, useMemo, useState } from 'react';
import { Loader2, Pencil, Plus, Search, Trash2, X } from 'lucide-react';
import { supabase } from '../../lib/supabase';

const configs={
 projects:{title:'Projects',description:'Manage archived student research and project records.',fields:[['title','Title'],['abstract','Abstract','textarea'],['authors','Authors'],['level','Level'],['session','Session'],['supervisor','Supervisor'],['keywords','Keywords'],['research_area','Research area'],['visibility','Visibility']]},
 events:{title:'Events',description:'Manage institutional events and their archive metadata.',fields:[['title','Title'],['description','Description','textarea'],['date','Date','date'],['time','Time'],['venue','Venue'],['event_category','Category'],['status','Status']]},
 media:{title:'Media',description:'Manage photos, videos, flyers and event media metadata.',fields:[['title','Title'],['description','Description','textarea'],['category','Category'],['year','Year'],['media_type','Media type'],['visibility','Visibility']]},
 meetings:{title:'Meetings',description:'Manage executive, congress, emergency and committee meetings.',fields:[['title','Title'],['meeting_type','Meeting type'],['year','Year'],['meeting_date','Date','date'],['venue','Venue'],['description','Description','textarea']]},
 administrations:{title:'Administrations',description:'Manage the succession history of NAMS FUTA administrations.',fields:[['name','Name'],['session','Session'],['start_date','Start date','date'],['end_date','End date','date'],['is_current','Current','checkbox']]},
 executives:{title:'Executives',description:'Manage executive council profiles and display order.',fields:[['name','Name'],['position','Position'],['administration_id','Administration ID'],['biography','Biography','textarea'],['display_order','Display order','number']]},
 announcements:{title:'Announcements',description:'Manage scheduled public news and announcements.',fields:[['title','Title'],['content','Content','textarea'],['category','Category'],['priority','Priority','number'],['published','Published','checkbox'],['publish_at','Publish at','datetime-local'],['expires_at','Expires at','datetime-local']]},
 alumni:{title:'Alumni',description:'Maintain the alumni directory.',fields:[['full_name','Full name'],['matric_number','Matric number'],['graduation_year','Graduation year'],['email','Email'],['phone','Phone'],['current_role','Current role']]},
 members:{title:'Membership',description:'Private membership records. Access remains controlled by RLS.',table:'membership_records',fields:[['full_name','Full name'],['matric_number','Matric number'],['level','Level'],['email','Email'],['phone','Phone'],['membership_status','Status']]},
};

export default function AdminModulePage({module}){
 const cfg=configs[module]; const table=cfg?.table||module; const [rows,setRows]=useState([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[query,setQuery]=useState(''),[editing,setEditing]=useState(null),[show,setShow]=useState(false),[saving,setSaving]=useState(false); const empty=()=>Object.fromEntries((cfg?.fields||[]).map(([n])=>[n,n==='checkbox'?false:''])); const [form,setForm]=useState(empty);
 async function load(){if(!supabase)return;setLoading(true);const r=await supabase.from(table).select('*').order('created_at',{ascending:false}).limit(200);if(r.error)setError(r.error.message);else setRows(r.data||[]);setLoading(false);}
 useEffect(()=>{load();},[table]); const filtered=useMemo(()=>rows.filter(r=>Object.values(r).join(' ').toLowerCase().includes(query.toLowerCase())),[rows,query]);
 function edit(r){setEditing(r);setForm(Object.fromEntries((cfg.fields||[]).map(([n])=>[n,r[n]??''])));setShow(true);} function create(){setEditing(null);setForm(empty());setShow(true);} function change(e){const {name,type,checked,value}=e.target;setForm(f=>({...f,[name]:type==='checkbox'?checked:value}));}
 async function save(e){e.preventDefault();setSaving(true);setError('');const payload={...form};Object.keys(payload).forEach(k=>{if(payload[k]==='')payload[k]=null;});const r=editing?await supabase.from(table).update(payload).eq('id',editing.id).select().single():await supabase.from(table).insert(payload).select().single();if(r.error)setError(r.error.message);else{await supabase.from('activity_logs').insert({action:editing?'update':'create',entity_type:table,entity_id:r.data?.id,metadata:{title:form.title||form.name||form.full_name}});setShow(false);await load();}setSaving(false);}
 async function remove(r){if(!confirm(`Delete this ${cfg.title.toLowerCase()} record?`))return;const x=await supabase.from(table).delete().eq('id',r.id);if(x.error)setError(x.error.message);else{await supabase.from('activity_logs').insert({action:'delete',entity_type:table,entity_id:r.id});await load();}}
 if(!cfg)return <main className="admin-shell"><div className="admin-empty"><p>This administration module is not configured yet.</p></div></main>;
 return <main className="admin-shell"><div className="admin-crud-head"><div><p className="eyebrow">ADMIN MODULE</p><h1>{cfg.title}</h1><p>{cfg.description}</p></div><button className="admin-primary" onClick={create}><Plus size={17}/> New record</button></div><div className="admin-toolbar"><label className="admin-search"><Search size={16}/><input placeholder="Search records…" value={query} onChange={e=>setQuery(e.target.value)}/></label><span>{filtered.length} records</span></div>{error&&<div className="form-error admin-error">{error}</div>}{loading?<div className="admin-empty"><Loader2 size={18} className="spin"/> Loading…</div>:filtered.length?<div className="admin-table-wrap"><table className="admin-table"><thead><tr>{(cfg.fields||[]).slice(0,4).map(([n,l])=><th key={n}>{l}</th>)}<th>Actions</th></tr></thead><tbody>{filtered.map(r=><tr key={r.id}>{cfg.fields.slice(0,4).map(([n])=><td key={n}>{typeof r[n]==='boolean'?(r[n]?'Yes':'No'):String(r[n]??'—').slice(0,90)}</td>)}<td><div className="admin-row-actions"><button onClick={()=>edit(r)}><Pencil size={15}/></button><button onClick={()=>remove(r)}><Trash2 size={15}/></button></div></td></tr>)}</tbody></table></div>:<div className="admin-empty"><p>No records yet.</p></div>}{show&&<div className="admin-modal-backdrop" onMouseDown={e=>e.target===e.currentTarget&&setShow(false)}><form className="admin-modal" onSubmit={save}><div className="admin-modal-head"><div><p className="eyebrow">{editing?'EDIT':'CREATE'}</p><h2>{editing?'Update record':'New record'}</h2></div><button type="button" onClick={()=>setShow(false)}><X/></button></div><div className="admin-form-grid">{cfg.fields.map(([n,label,type])=><label key={n} className={type==='textarea'?'full':''}>{label}{type==='textarea'?<textarea name={n} rows="4" value={form[n]??''} onChange={change}/>:type==='checkbox'?<input type="checkbox" name={n} checked={Boolean(form[n])} onChange={change}/>:<input type={type||'text'} name={n} value={form[n]??''} onChange={change}/>}</label>)}</div><div className="admin-modal-actions"><button type="button" className="admin-secondary" onClick={()=>setShow(false)}>Cancel</button><button className="admin-primary" disabled={saving}>{saving?<><Loader2 size={16} className="spin"/> Saving…</>:<><Plus size={16}/> Save</>}</button></div></form></div>}</main>;
}
