import { useEffect, useState } from 'react';
import { Loader2, Plus, ShieldCheck, UserCheck, UserX } from 'lucide-react';
import { supabase } from '../../lib/supabase';
import { getCurrentProfile } from '../../lib/auth';

export default function AdminAdmins(){
  const [admins,setAdmins]=useState([]),[profile,setProfile]=useState(null),[loading,setLoading]=useState(true),[busy,setBusy]=useState(''),[error,setError]=useState(''),[message,setMessage]=useState('');
  const [form,setForm]=useState({email:'',password:'',username:'',full_name:'',role:'admin'});
  const canSuper=profile?.role==='super_admin';
  async function invoke(body){const result=await supabase.functions.invoke('admin-account-management',{body});if(result.error)throw new Error(result.error.message||'Account service failed.');if(result.data?.error)throw new Error(result.data.error);return result.data;}
  async function load(){setLoading(true);setError('');try{const data=await invoke({action:'list'});setAdmins(data.admins||[]);}catch(e){setError(e.message);}finally{setLoading(false);}}
  useEffect(()=>{getCurrentProfile().then(({profile:current})=>{setProfile(current);load();});},[]);
  async function create(event){event.preventDefault();setBusy('create');setError('');setMessage('');try{await invoke({action:'create',...form});setForm({email:'',password:'',username:'',full_name:'',role:'admin'});setMessage('Administrator account created.');await load();}catch(e){setError(e.message);}finally{setBusy('');}}
  async function toggle(admin){setBusy(admin.id);setError('');setMessage('');try{await invoke({action:'set_active',user_id:admin.id,is_active:!admin.is_active});setMessage(`${admin.full_name||admin.username||'Administrator'} is now ${admin.is_active?'inactive':'active'}.`);await load();}catch(e){setError(e.message);}finally{setBusy('');}}
  async function changeRole(admin){if(!canSuper)return;const role=admin.role==='admin'?'super_admin':'admin';setBusy(`role:${admin.id}`);setError('');setMessage('');try{await invoke({action:'set_role',user_id:admin.id,role});setMessage('Administrator role updated.');await load();}catch(e){setError(e.message);}finally{setBusy('');}}
  return <main className="admin-shell"><div className="admin-crud-head"><div><p className="eyebrow">CONTINUITY & SECURITY</p><h1>Administrators</h1><p>Manage privileged archive accounts through the protected account-management service.</p></div></div>
    {error&&<div className="form-error admin-error">{error}</div>}{message&&<div className="admin-success">{message}</div>}
    <section className="admin-account-grid"><form className="admin-account-card" onSubmit={create}><div className="admin-section-head"><div><p className="eyebrow">CREATE ACCOUNT</p><h2>New administrator</h2></div><ShieldCheck size={20}/></div><label>Full name<input value={form.full_name} onChange={e=>setForm(v=>({...v,full_name:e.target.value}))} /></label><label>Username<input value={form.username} onChange={e=>setForm(v=>({...v,username:e.target.value}))} /></label><label>Email<input type="email" required value={form.email} onChange={e=>setForm(v=>({...v,email:e.target.value}))} /></label><label>Temporary password<input type="password" minLength="10" required value={form.password} onChange={e=>setForm(v=>({...v,password:e.target.value}))} /><small>Minimum 10 characters.</small></label><label>Role<select value={form.role} onChange={e=>setForm(v=>({...v,role:e.target.value}))} disabled={!canSuper}><option value="admin">Admin</option><option value="super_admin">Super admin</option></select></label><button className="admin-primary" disabled={busy==='create'}>{busy==='create'?<><Loader2 size={16} className="spin"/> Creating…</>:<><Plus size={16}/> Create administrator</>}</button></form>
    <div className="admin-account-card"><div className="admin-section-head"><div><p className="eyebrow">ACTIVE ACCOUNTS</p><h2>Access roster</h2></div></div>{loading?<div className="admin-empty"><Loader2 size={18} className="spin"/> Loading…</div>:<div className="admin-account-list">{admins.map(admin=><div className="admin-account-row" key={admin.id}><div><strong>{admin.full_name||admin.username||'Unnamed administrator'}</strong><span>{admin.username?`@${admin.username} · `:''}{admin.role} · {admin.is_active?'Active':'Inactive'}</span></div><div className="admin-row-actions"><button onClick={()=>toggle(admin)} disabled={busy===admin.id} title={admin.is_active?'Deactivate account':'Activate account'}>{admin.is_active?<UserX size={15}/>:<UserCheck size={15}/>}</button>{canSuper&&<button onClick={()=>changeRole(admin)} disabled={busy===`role:${admin.id}`} title="Toggle admin role"><ShieldCheck size={15}/></button>}</div></div>)}{!admins.length&&<div className="admin-empty"><p>No privileged accounts found.</p></div>}</div>}</div></section>
  </main>;
}
